services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments
    ports:
      - "5432:5432"

#  backend-1:
#    #  image: danieltenorio/payment-processor:latest
#    build: .
#    container_name: backend-1
#    networks:
#      - backend
#      - payment-processor
#    environment:
#      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
#      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
#    ports:
#      - "9999:8080"
#    deploy:
#      resources:
#        limits:
#          cpus: "0.75"
#          memory: "175MB"
#
#  backend-2:
#    #  image: danieltenorio/payment-processor:latest
#    build: .
#    container_name: backend-2
#    networks:
#      - backend
#      - payment-processor
#    environment:
#      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
#      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
#    deploy:
#      resources:
#        limits:
#          cpus: "0.75"
#          memory: "175MB"
#
#networks:
#  backend:
#    driver: bridge
#  payment-processor:
#    external: true